- src_py/SConstruct
@zivmo99 Please perform experiment after compiling in release with this change
> Optimizing compilation in release

- README.md
- src_py/SConstruct
- Add explanation how to install rebar and eigen
> Add eigen flag to sconstruct

- src_erl/Communication_Layer/http_Nerlserver/src/Client/clientStateHandler.erl
- src_erl/Communication_Layer/http_Nerlserver/src/Client/clientStatem.erl
- src_erl/Communication_Layer/http_Nerlserver/src/Client/vectorHandler.erl
- src_erl/Communication_Layer/http_Nerlserver/src/MainServer/ackHandler.erl
- src_erl/Communication_Layer/http_Nerlserver/src/MainServer/actionHandler.erl
- src_erl/Communication_Layer/http_Nerlserver/src/MainServer/initHandler.erl
- src_erl/Communication_Layer/http_Nerlserver/src/MainServer/mainGenserver.erl
- src_erl/Communication_Layer/http_Nerlserver/src/Router/routerGenserver.erl
- src_erl/Communication_Layer/http_Nerlserver/src/Router/routingHandler.erl
- src_erl/Communication_Layer/http_Nerlserver/src/erl_client.erl
- src_erl/Communication_Layer/http_Nerlserver/src/jsonParser.erl
- src_erl/Communication_Layer/http_Nerlserver/src/nerlNetServer_app.erl
- src_erl/Communication_Layer/http_Nerlserver/src/source/castingHandler.erl
- src_erl/Communication_Layer/http_Nerlserver/src/source/csvHandler.erl
- src_erl/Communication_Layer/http_Nerlserver/src/source/sourceStatem.erl
- src_py/NerlNetController.py
now when a client receives a predict batch it inclueds the batchNumber
and input name, so main server would be able to identify this specific
batch later on
> fixed warnings, added predict protocol

- src_py/apiServer/apiServer.py
- src_py/apiServer/globalVars.py
- src_py/apiServer/jsonMapParser.py
- src_py/apiServer/map.json
- src_py/apiServer/networkMap.py
- src_py/apiServer/receiver.py
- src_py/apiServer/transmitter.py
Required for Tal to make changes in Erlang.
> Api server merged

- src_erl/Communication_Layer/http_Nerlserver/src/jsonHandler.erl
- src_erl/Communication_Layer/http_Nerlserver/src/jsonParser.erl
- src_erl/Communication_Layer/http_Nerlserver/src/nerlNetServer_app.erl
fixed routers issues
added json pathes receive from python
> Communication layer

- NerlnetInstall.sh
- NerlnetStartup.sh
Checked and works on Ubuntu 20.04
> [NERLNET_SCRIPTS] fix nerlnet install and nerlnet startup issues

- inputJsonFiles/Architecture/jsonArch1PC1Worker.json
- inputJsonFiles/experimentsFlow/expFlowJson.json
- jsonPath
- src_erl/Communication_Layer/http_Nerlserver/src/MainServer/mainGenserver.erl
- src_erl/Communication_Layer/http_Nerlserver/src/nerlNetServer_app.erl
- src_py/apiServer/apiServer.py
- src_py/apiServer/globalVars.py
- src_py/apiServer/receiver.py
- src_py/apiServer/transmitter.py
.erl changes where requested by Tal, and must be approved by him!
> Working flow training->prediction

- src_py/apiServer/networkComponents.py
> Very basic function to check identical addresses (ports)

- .github/workflows/pr.yml
- Dockerfile
- NerlnetInstall.sh
This YAML file defines a workflow that runs on every  pull request targeting the master branch. The workflow consists of a single job called build, which runs on the latest version of Ubuntu.
The job contains three steps:
The first step checks out the repository code.
The second step installs the curl package, which may be needed by the NerlnetInstall.sh script. The third step makes the NerlnetInstall.sh script executable and runs it.
> ci: add pipeline

- .github/workflows/update_image.yml
Just upgrade and add option to run this pipeline manually
> ci: upgrade pipline

- src_erl/erlBridge/nerlNIF.erl
- src_erl/erlBridge/nerlTests.erl
- Add test to function nerltensor_conversion
- fix an issue with encode/decode calls of nerltensor_conversion
> [nerlNIF] nerltensor_conversion fix an issue

- inputJsonFiles/Architecture/arch_1PC8WorkerSynth.json
- inputJsonFiles/Architecture/arch_2PC3WorkerSynthFed.json
- inputJsonFiles/Architecture/arch_2PC8Worker2SourcesSynthFed.json
- inputJsonFiles/Architecture/arch_2PC8WorkerSynthFed.json
- inputJsonFiles/Architecture/arch_3PC8WorkerSynthFed.json
- inputJsonFiles/ConnectionMap/conn_2Router2Clients2Source.json
- inputJsonFiles/experimentsFlow/exp_8Worker1SourceSynth.json
- inputJsonFiles/experimentsFlow/exp_8Worker2SourceSynth.json
- src_cpp/opennnBridge/get_set_weights.h
- src_erl/Communication_Layer/http_Nerlserver/src/Client/clientStatem.erl
- src_erl/Communication_Layer/http_Nerlserver/src/MainServer/mainGenserver.erl
- src_erl/Communication_Layer/http_Nerlserver/src/init/jsonParser.erl
- src_erl/Communication_Layer/http_Nerlserver/src/nerlNetServer_app.erl
- src_erl/Communication_Layer/http_Nerlserver/src/source/sourceStatem.erl
- src_erl/erlBridge/nerlTensor.hrl
- src_erl/erlBridge/workers/workerFederatedClient.erl
- src_erl/erlBridge/workers/workerFederatedServer.erl
- src_erl/erlBridge/workers/workerGeneric.erl
- src_py/apiServer/apiServer.py
- src_py/apiServer/globalVars.py
- src_py/apiServer/receiver.py
- src_py/apiServer/transmitter.py
Includes:
-APIserver ack fixes
-source split mode (send whole csv data file to all sources / split data per source)
-missed federated message workaround (test if fixed)
-missed batches count in communication command
-cleaning, etc.
> Comm stats

- src_py/apiServer/apiServer.py
> normalization option fix

- src_py/nerlPlanner/Handlers.py
- src_py/nerlPlanner/JsonDistributedConfig.py
- src_py/nerlPlanner/main.py
- Add remove button to routers
- Fix exception of frequency
> [NERLPLANNER] Add remove button to routers

- src_cpp/opennnBridge/eigenTensorTypes.h
- src_cpp/opennnBridge/nerlLayer.cpp
- src_cpp/opennnBridge/nerlLayer.h
- src_cpp/opennnBridge/nerlworker.cpp
- src_cpp/opennnBridge/nerlworker.h
- src_py/nerlPlanner/WinWorkerDialogDefnitions.py
- Add nerlnet namespace
- Add CNN child layer
- Add OpenNN as child of NerlnetWorker
> [NERLPLANNER] Integration NIF Phase

- src_py/nerlPlanner/Handlers.py
- src_py/nerlPlanner/HandlersGlobals.py
- src_py/nerlPlanner/JsonDistributedConfig.py
- Add get_client_workers method
- fix combo box of workers without occupied workers
> [NERLPLANNER]Fix issues with client's workers

- README.md
- src_cpp/common/nerlWorkerFunc.h
- src_cpp/opennnBridge/nerlWorkerOpenNN.cpp
- src_erl/NerlnetApp/src/Bridge/neural_networks_testing_models.hrl
- src_py/apiServer/apiServer.py
- src_py/apiServer/singleton.py
> Fix push problem and add flatten layer and assert

- src_erl/NerlnetApp/src/Bridge/onnWorkers/workerGeneric.erl
- src_erl/NerlnetApp/src/Client/clientStatem.erl
- src_erl/NerlnetApp/src/Client/clientWorkersFunctions.erl
- src_erl/NerlnetApp/src/MainServer/mainGenserver.erl
- src_py/apiServer/NerlComDB.py
- src_py/apiServer/apiServer.py
- src_py/apiServer/apiServerHelp.py
- src_py/apiServer/decoderHttpMainServer.py
- src_py/apiServer/experiment_phase.py
- src_py/apiServer/nerl_model_db.py
- Add distributed token to NerlnetAPP and ApiServer
- remove redundant import from nerl_model_db
> [ModelDB] Add distributed token

- src_erl/NerlnetApp/src/Client/clientStatem.erl
- src_erl/NerlnetApp/src/MainServer/initHandler.erl
- src_erl/NerlnetApp/src/MainServer/mainGenserver.erl
- src_erl/NerlnetApp/src/Source/castingHandler.erl
- src_erl/NerlnetApp/src/Source/sourceStatem.erl
- src_py/apiServer/transmitter.py
- BatchId can be greater than source piece csv!!!
> [SOURCE] Epochs are supported by source

- src_erl/NerlnetApp/src/Source/sourceSendingPolicies.erl
- src_erl/NerlnetApp/src/Source/sourceStatem.erl
- RR and Random were never selected - Fixed
- Optimization of sending RR and Random
> [SOURCE] Critical Bug - RR and Random

- src_erl/NerlnetApp/src/nerlnetApp_app.erl
- src_py/nerlPlanner/Definitions.py
> [FED] Update Nerlnet Version

- src_cpp/opennnBridge/nerlWorkerOpenNN.cpp
> add parsing

- Dockerfile
> Revert "docker - erlang installation change back to apt"
